name: Deployment Notification

on:
  pull_request:
    types: [ opened ]

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Decentraland Unity-Renderer Deployment Notification
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@main
        with:
          message: |
            Hello world
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}